import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const firaCode = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chase's Personal Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: basePath

  return (
    <html lang="en">
      <link rel='icon' type='image/png' href='/static/favicon.png' />
      <body>
        <main className={firaCode.className}>
          {children}
        </main>
      </body>
    </html>
  );
}
